language: python
matrix:
  include:
    - name: "Ubuntu"
      python: 3.8
      dist: bionic
    - name: "macOS"
      os: osx
      osx_image: xcode12
      language: generic
      before_install:
        - pip3 install virtualenv
        - virtualenv -p python3 ~/venv
        - source ~/venv/bin/activate
script: make coverage