language: python
matrix:
  include:
    - name: "Ubuntu"
      python: 3.8
      dist: bionic
    - name: "macOS"
      os: osx
      osx_image: xcode12
      python: 3.8
      language: shell
script: make coverage