language: python
matrix:
  include:
    - name: "Ubuntu"
      python: 3.8
      dist: bionic
    - name: "macOS"
      os: osx
      osx_image: xcode12
      env: INSTALL_TYPE=macpython VERSION=3.8 VENV=venv
      language: shell
script: make coverage